# Generated by Django 5.1.4 on 2025-01-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, help_text='Main content of the blog post, generated by AI.'),
        ),
    ]
