from django.db import models

class BlogPost(models.Model):
    """
    Model to store information about travel blog posts.
    """
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=100, default="AI", help_text="Name of the content creator, default is AI.")
    pub_date = models.DateTimeField(auto_now_add=True, help_text="Date and time when the post is published.")
    tags = models.ManyToManyField('Tag', blank=True, help_text="Tags related to the blog post.")
    content = models.TextField(help_text="Main content of the blog post, generated by AI.")
    image_url = models.URLField(blank=True, null=True, help_text="URL of the image fetched from Unsplash.")
    description = models.CharField(max_length=500, blank=True, help_text="Short description or summary of the post.")

    def __str__(self):
        return self.title


class Tag(models.Model):
    """
    Model to store tags for blog posts.
    """
    name = models.CharField(max_length=50, unique=True, help_text="Name of the tag.")

    def __str__(self):
        return self.name